
# ID & access management

Have you ever thought about any of the following questions?

How can we uniquely identify the different system users?
How can a user prove who they are to the system?
How can we help prevent an attacker from pretending to be a legitimate user?
How can we decide what a user should access? How can we enforce such a decision?
How can we know what a user is doing after logging in so that we can hold them accountable for their actions?


concepts and processes:

Identification
Authentication
Strong passwords and Multi-Factor Authentication (MFA)
Authorisation and Access Control
Logging and Auditing



Learning Objectives
By the end of this room, you should have gained a solid understanding of the following processes and concepts:

Identification
Authentication
Authorisation
Accountability
Access Control Models
Single Sign-On




Identification, Authentication, Authorisation, and Accountability (IAAA) are four pillars of information security

ID =  process of verifying who the user is. It starts with the user claiming a specific identity.  (unique identifier such as an email address, a username, or an ID number.)

Authentication = process of ensuring that the user is who they claim to be.

Authorisation = determines what the user is allowed to access.  roles and permissions based on the user’s job function or level of clearance.

Accountability tracks user activity to ensure they are responsible for their actions



## id

Identification is how a user (or process or system) claims a specific identity. 

Identification can also be achieved through a number such as:

National ID number
Student ID number
Passport number
Mobile phone number


## auth

Authentication is the process of verifying the identity of a user or system

Authentication is proving the identity of the user (or system or process). 
Something you know    passwords/ PINs
Something you have    mobile phone/ Yubikey etc
Something you are     biometrics

Somewhere you are (logical/physical location)
Something you do (behaviour)


## Authorisation and Access Control

authorisation decides what a user should be able to access, while access control enforces the set policy



## Accountability and Logging

Accountability ensures that users are accountable for the actions they perform on a system.
Accountability is possible if we have auditing capabilities, which usually require proper logging functionality.


Logging
Logging is the process of recording events that occur within a system. This process includes user actions, system events, and errors.

Security Information and Event Management (SIEM) is a technology that aggregates log data from multiple sources and analyses it for signs of security threats.



## ID management

Identity Management (IdM) includes all the necessary policies and technologies for identification, authentication, and authorisation.

authorised people have access to the assets and resources needed for their work while unauthorised people are denied access.

IdM helps organisations protect sensitive data and maintain compliance with regulations.

Identity and Access Management (IAM)
processes and technologies to manage and secure digital identities and access rights. IAM systems include a variety of functions, such as user provisioning, access control, identity governance, and compliance management




## attacks against auth

This attack is considered a replay attack. 


## access control models

A system controls access to various resources
Discretionary Access Control (DAC)
Role-Based Access Control (RBAC)
Mandatory Access Control (MAC)


Discretionary Access Control

When using DAC, the resource owner will explicitly add users with the proper permissions.


Role-Based Access Control

Each user has one or more roles or functional positions 
they are authorised to access different resources based on their roles.
users are put into different groups based on their roles. 


Mandatory Access Control

An operating system using Mandatory Access Control (MAC) would prioritise security and significantly limit users’ abilities

users do not need to carry out tasks beyond the strictly necessary.
no new software




## single sign on

Users need to access various sources to carry out their daily work routines
Accessing these resources requires the user to have login credentials for successful authentication. 

Single Sign-On (SSO) tackles this problem. Instead of a user having to remember multiple usernames and passwords, they only need to remember a single set of login credentials.

Single sign-on (SSO) is a session and user authentication service that permits a user to use one set of login credentials -- for example, a username and password -- to access multiple applications.






















