
# risk management

Threat: an intentional or accidental event that can compromise the security of an information system. Examples include hacking, phishing attacks, human error, and natural disasters.

Vulnerability: a software, hardware, or network weakness that cybercriminals can exploit to gain unauthorised access or compromise a system.

Asset: a valuable resource or component (tangible or intangible) that an organisation relies upon to achieve its objectives.

Risk: the probability of a threat source exploiting an existing vulnerability and resulting in adverse business effects.

Risk Management (RM): the process of identifying, assessing, and mitigating risk to maintain acceptable levels.



A threat is a potential harm or danger to an individual, organisation, or system. Threats can be classified into three main categories: human-made, technical, or natural.

Terrorism
Wars and conflicts
Riots and civil unrest
Cyberattacks
Industrial accidents
Arson


Technical threats: These threats result from technological failures, malfunctions, or vulnerabilities.

Power outages
Software and hardware failures
Data breaches
Network and system vulnerabilities
Equipment malfunctions


Natural threats:
Earthquakes
Floods

VULNERABILITY
A vulnerability is a weakness in the system or software that can be exploited by a threat to cause harm.

a weakness that can be exploited by malicious individuals, groups, or external factors to gain unauthorised access, cause damage, or compromise the integrity, availability, or confidentiality of a system, data, or network.


ASSET
An asset is an economic resource owned or controlled by an individual, company, or government.
Assets include cash and cash equivalents, accounts receivable, investments, stock, equipment, real estate, and intellectual property.

examples of assets in an information system include:

Hardware: Servers, workstations, routers, switches, firewalls, and other physical devices used to store, process, and transmit information.

Software: Operating systems, applications, databases, and other programs that enable the organisation to perform its functions efficiently and effectively.

Data: Organisational data, which includes sensitive information such as customer records, financial data, intellectual property, and personal data of employees.
Documentation: Manuals, policy documents.





RISK

Risk is the probability of a threat source exploiting an existing vulnerability (in an asset) and resulting in adverse business effects.

Risk is the potential of encountering unforeseen events or circumstances that may lead to a loss, damage, or negative outcome. 

business context, it is the probability of a threat source exploiting an existing vulnerability and resulting in adverse business effects.

threat/ vulnerability/ asset = risk




ASSESS RISK

- Threats: What are the threats that you need to consider?

- Vulnerabilities: What are the vulnerabilities that you have to deal with?

- Impact: What would be the impact if a threat exploited a vulnerability?

- Likelihood: What is the likelihood of this vulnerability being exploited?

Threats
physical damage = water leak, fire, power loss
outsider threat = ransomware 

ALE before == Loss Value

value = ALE before - ALE after - cost of safeguard




RISK ANALYSIS
            
laptop = theft , 2500, EF 100% SLE 2500, ARO 0.05, safeguard cost $45 EF post safeguard /              
phone = theft, 1250, EF 100% ARO .35, cost safeguard $10, EF post safeguard 40% /           
workstation = disk fail, 3000, SLE 2100, EF 70%, 2100 ARO 0.20, safegurad cost $200 EF post safe 0% 
workstation = malware , 3000, EF 10%  ARO 0.05 cost safe $250 EF post safe 0%      
workstation = screen fail, 3000 EF 85% ARO .35  cost safe $75 post safe 5%         
laptop = theft, 2500 EF 100% ARO .20 cost safe $75 post EF 24%                      
office = 0 EF 100% ARO .10 cost safe $750 post EF 15%                               

reject all = fail
approvae all = fail

A = approve
R = reject

A/A/A/A/R/A/R
R/R/A/A/R/A/R











Risk Assumptions: The fact that this company handles the accounting data of its clients increases the risk of being targeted by adversaries that would try to profit from stealing such data. Unless proper measures are taken, the likelihood of success is relatively high, and the impact would be disastrous for the company’s image.

Risk Constraints: The primary constraints are expected to be budget-related. Safeguarding the data requires improving physical and cyber security; it entails conducting cyber security training and hiring new personnel.

Risk Tolerance: Considering the type of business, the risk of data theft cannot be tolerated. Tolerating data theft would lead to the whole company going out of business.
Priorities and Trade-offs: The priority is to maintain a trustworthy image of a company that can conduct its business with confidentiality and integrity.










risk management
  Avoid Risk
  Transfer Risk (or Share Risk)
  Mitigate Risk (or Reduce Risk)
  Accept Risk

Avoid Risk: If a company decides to eliminate the activity that leads to the risk, that would be risk avoidance. A bank might decide that all employees’ computers cannot access the Internet to protect its systems against all online threats. An organisation might instruct its employees to work exclusively using the workstations on its premises to prevent data from being stolen.

Transfer Risk: A company might consider the risk too high to handle, so it decides to purchase insurance. That would be risk transference or risk sharing. A publishing house might buy insurance against fire, for instance.

Mitigate Risk: A company might invest in countermeasures to reduce risk to an acceptable level; this would be risk mitigation. To protect against computer viruses, a company might install antivirus on all its computers instead of blocking access to the Internet and glueing the USB ports.
Accept Risk: Sometimes, the countermeasure cost exceeds the loss incurred if the risk is realised.


Quantitative risk analysis would help us decide whether a specific control is justified from the business perspective. Implementing a safeguard won’t make sense unless its benefit outweighs its cost.




Quantitative Analysis

Quantitative risk analysis would help us decide whether a specific control is justified from the business perspective

-  Implementing a safeguard won’t make sense unless its benefit outweighs its cost.



value of safeguard = ALE (before safeguard) - ALE (post safeguard) - annual cost for safeguard

















implement safeguard
laptop  (full risk $1500 safeguard cost)
-laptop  (theft risk)
-laptop  (fall risk, $1500 safety)

-server (risk: power supply, $400 safety, worth $10k)
server ($3000 safety, worth $10k)
-server (disk fail, $70 safety, worth $10k)

phone (encrypted, $20 cost safety)





Finding and adding new risks
Eliminating risks that are no longer relevant
Assessing our responses to existing risks

Effectiveness = Responding to an assessed risk does not mark the end of the story
Change
Compliance







laptop = theft from office  $2500 value safety cost $45 / approve

phone= theft $1250 value  safety cost $10 / approve

workstation= disk fail 3000 value safety cost $200  / approve




workstation=  malware  3000 value antivirus $75 / approve

workstation= screen fail 3000 value backup screen $250 / reject

laptop = theft 2500 value encryption $75 / -reject

office = intrusion & theft $0 value sfaety PIN $750  / -approve
















